services:
  localstack:
    extends:
      file: docker-compose.deps.yml
      service: localstack
    environment:
      - GATEWAY_LISTEN=127.0.0.1
    ports:
      - '4566:4566'
      - '4510-4559:4510-4559'